### ISSUE TITLE
{ name: 'HTTPError', code: 404, message: 'Not Found' }

### ISSUE THREAD

**Issue by claytondukes** [ricardocasares/kbme#15]
Sorry if this is a noob-ish question, but how can I fix this?

I thought maybe it was Jira not allowing API calls, but some googling says it's enabled by default.
I tried `KBME_JIRA="http://internal-url.blah/rest/api/2/"` and KBME_JIRA="http://internal-url.blah"` and KBME_JIRA="http://internal-url.blah:8080"`.

(there's an IPtables redirect on that server to forward port 80 to 8080, but I tried both to no avail.)

I also tried by IP.

**Comment by alazurenko** [comment]
Hello, @claytondukes 

Could you please try to set an endpoint in .env?

For instance,
```
KBME_JIRA="http://server-url.com"
KBME_ENDPOINT="%jira/jira/rest/api/2/search?jql=%jql&expand=changelog"
```
